### ISSUE TITLE
Bring kernel flake up-to-date

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/linux#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Existing kernel Nix flake is out-of-date, that should be fixed (the version and config)

**Comment by rvolosatovs** [comment]
Best to be done after #4

**Comment by jarkkojs** [comment]
I'm finalizing a bug fix for a firmware update issue in the SNP kernel. I'll put a note here, once the fix is done. After that I'll also update SNP patches to the latest versions but these need to happen in this order. @rvolosatovs @puiterwijk @rvolosatovs

**Comment by dpal** [comment]
Was done.
